export const CAP_NHAT = "22/07/2026";

export const banks = [
  { id: "vcb", name: "Vietcombank", short: "VCB", color: "#0B7A5E" },
  { id: "tcb", name: "Techcombank", short: "TCB", color: "#C0392B" },
  { id: "bidv", name: "BIDV", short: "BIDV", color: "#0E5A8A" },
  { id: "vpb", name: "VPBank", short: "VPB", color: "#2E6DB4" },
  { id: "mb", name: "MB Bank", short: "MB", color: "#1B2E42" },
  { id: "acb", name: "ACB", short: "ACB", color: "#1B4FA0" },
  { id: "tpb", name: "TPBank", short: "TPB", color: "#7A2E8A" },
  { id: "vib", name: "VIB", short: "VIB", color: "#0A6247" },
  { id: "stb", name: "Sacombank", short: "STB", color: "#0E5A8A" },
  { id: "shb", name: "SHB", short: "SHB", color: "#E09B2D" },
  { id: "hdb", name: "HDBank", short: "HDB", color: "#C0392B" },
  { id: "seab", name: "SeABank", short: "SEA", color: "#C0392B" },
];

export const bankById = (id) => banks.find((b) => b.id === id);

export const NHOM_HO_SO = [
  {
    id: "chuyen-khoan",
    label: "Nhận lương chuyển khoản",
    mo_ta: "Lương về tài khoản ngân hàng đều đặn, có sao kê 3–6 tháng.",
    han_muc: "Tối đa 20 lần lương, trần 500 triệu",
    giay_to: ["CCCD", "Sao kê lương 3 tháng", "Hợp đồng lao động"],
    lai_suat: "12,5% – 18%/năm",
  },
  {
    id: "tien-mat",
    label: "Nhận lương tiền mặt",
    mo_ta: "Không có sao kê, chứng minh bằng bảng lương có dấu và BHXH.",
    han_muc: "Tối đa 10 lần lương, trần 200 triệu",
    giay_to: ["CCCD", "Bảng lương có dấu", "Sổ BHXH / VssID"],
    lai_suat: "18% – 26%/năm",
  },
  {
    id: "bao-hiem",
    label: "Có bảo hiểm nhân thọ",
    mo_ta: "Hợp đồng đóng phí từ 12 tháng trở lên, phí năm từ 10 triệu.",
    han_muc: "Tối đa 100 lần phí năm, trần 300 triệu",
    giay_to: ["CCCD", "Hợp đồng bảo hiểm", "Biên lai đóng phí"],
    lai_suat: "16% – 24%/năm",
  },
  {
    id: "hoa-don",
    label: "Có hóa đơn điện nước",
    mo_ta: "Hóa đơn đứng tên bạn, thanh toán đều 3 tháng gần nhất.",
    han_muc: "Tối đa 70 triệu",
    giay_to: ["CCCD", "Hóa đơn điện/nước 3 tháng", "Sổ hộ khẩu / KT3"],
    lai_suat: "20% – 30%/năm",
  },
];

const DO_THI_LON = [
  "TP. Hồ Chí Minh", "Hà Nội", "Đà Nẵng", "Bình Dương", "Đồng Nai",
  "Hải Phòng", "Cần Thơ",
];

export const products = [
  {
    slug: "vcb-mua-nha-an-cu",
    bankId: "vcb",
    ten: "An cư lạc nghiệp",
    loai: "the-chap",
    muc_dich: ["mua-nha", "xay-sua"],
    tsdb: ["so-do", "so-hong", "can-ho"],
    lai_suat_uu_dai: 5.5,
    thang_uu_dai: 12,
    bien_do: 3.5,
    lai_suat_co_so: 5.4,
    han_muc_min: 300,
    han_muc_max: 20000,
    ltv: 70,
    thoi_han_max: 300,
    giai_ngan_ngay: 14,
    thu_nhap_min: 20,
    phi_tra_truoc_han: "1,5% năm 1–2, sau đó miễn phí",
    phi_tham_dinh: "Miễn phí",
    diem: 4.7,
    uu_diem: ["Lãi suất ưu đãi thấp nhất thị trường", "Miễn phí thẩm định tài sản", "Thời hạn tới 25 năm"],
    nhuoc_diem: ["Thẩm định hồ sơ khắt khe", "Yêu cầu chứng minh thu nhập rõ ràng"],
  },
  {
    slug: "tcb-nha-moi",
    bankId: "tcb",
    ten: "Gia đình linh hoạt",
    loai: "the-chap",
    muc_dich: ["mua-nha", "kinh-doanh"],
    tsdb: ["so-do", "so-hong", "can-ho"],
    lai_suat_uu_dai: 5.9,
    thang_uu_dai: 24,
    bien_do: 3.8,
    lai_suat_co_so: 5.6,
    han_muc_min: 500,
    han_muc_max: 30000,
    ltv: 80,
    thoi_han_max: 420,
    giai_ngan_ngay: 10,
    thu_nhap_min: 25,
    phi_tra_truoc_han: "2% năm 1–3",
    phi_tham_dinh: "3 triệu",
    diem: 4.6,
    uu_diem: ["Ưu đãi kéo dài 24 tháng", "Tỷ lệ vay tới 80% giá trị", "Thời hạn tới 35 năm"],
    nhuoc_diem: ["Phí trả nợ trước hạn cao", "Có phí thẩm định tài sản"],
  },
  {
    slug: "bidv-an-gia",
    bankId: "bidv",
    ten: "An gia lập nghiệp",
    loai: "the-chap",
    muc_dich: ["mua-nha", "xay-sua"],
    tsdb: ["so-do", "so-hong"],
    lai_suat_uu_dai: 5.7,
    thang_uu_dai: 18,
    bien_do: 3.4,
    lai_suat_co_so: 5.3,
    han_muc_min: 200,
    han_muc_max: 15000,
    ltv: 75,
    thoi_han_max: 360,
    giai_ngan_ngay: 15,
    thu_nhap_min: 15,
    phi_tra_truoc_han: "1% năm 1–3",
    phi_tham_dinh: "Miễn phí",
    diem: 4.5,
    uu_diem: ["Biên độ thả nổi thấp", "Phí trả trước hạn chỉ 1%", "Mạng lưới chi nhánh rộng"],
    nhuoc_diem: ["Thời gian xử lý chậm hơn", "Yêu cầu tài sản tại đô thị"],
  },
  {
    slug: "acb-nha-o",
    bankId: "acb",
    ten: "Vay mua nhà ACB",
    loai: "the-chap",
    khu_vuc: DO_THI_LON,
    muc_dich: ["mua-nha"],
    tsdb: ["so-hong", "can-ho"],
    lai_suat_uu_dai: 6.2,
    thang_uu_dai: 24,
    bien_do: 3.2,
    lai_suat_co_so: 5.5,
    han_muc_min: 300,
    han_muc_max: 25000,
    ltv: 75,
    thoi_han_max: 300,
    giai_ngan_ngay: 12,
    thu_nhap_min: 20,
    phi_tra_truoc_han: "1,5% năm 1–2",
    phi_tham_dinh: "2 triệu",
    diem: 4.4,
    uu_diem: ["Biên độ sau ưu đãi thấp nhất", "Duyệt nhanh với căn hộ dự án"],
    nhuoc_diem: ["Lãi suất ưu đãi không thấp nhất", "Chưa nhận đất nông nghiệp"],
  },
  {
    slug: "vpb-kinh-doanh",
    bankId: "vpb",
    ten: "Vốn kinh doanh thế chấp",
    loai: "the-chap",
    khu_vuc: DO_THI_LON,
    muc_dich: ["kinh-doanh"],
    tsdb: ["so-do", "so-hong"],
    lai_suat_uu_dai: 6.5,
    thang_uu_dai: 12,
    bien_do: 4.0,
    lai_suat_co_so: 5.8,
    han_muc_min: 200,
    han_muc_max: 10000,
    ltv: 70,
    thoi_han_max: 180,
    giai_ngan_ngay: 7,
    thu_nhap_min: 30,
    phi_tra_truoc_han: "2% năm 1",
    phi_tham_dinh: "2 triệu",
    diem: 4.2,
    uu_diem: ["Giải ngân nhanh trong 7 ngày", "Nhận hộ kinh doanh cá thể"],
    nhuoc_diem: ["Biên độ thả nổi cao", "Thời hạn tối đa 15 năm"],
  },
  {
    slug: "vib-mua-xe",
    bankId: "vib",
    ten: "Vay mua ô tô VIB",
    loai: "the-chap",
    muc_dich: ["mua-xe"],
    tsdb: ["o-to"],
    lai_suat_uu_dai: 7.5,
    thang_uu_dai: 12,
    bien_do: 3.5,
    lai_suat_co_so: 5.9,
    han_muc_min: 100,
    han_muc_max: 5000,
    ltv: 85,
    thoi_han_max: 96,
    giai_ngan_ngay: 3,
    thu_nhap_min: 15,
    phi_tra_truoc_han: "2% năm 1–2",
    phi_tham_dinh: "Miễn phí",
    diem: 4.5,
    uu_diem: ["Vay tới 85% giá trị xe", "Giải ngân trong 3 ngày", "Nhận cả xe cũ dưới 5 năm"],
    nhuoc_diem: ["Lãi suất cao hơn vay bất động sản", "Thời hạn tối đa 8 năm"],
  },
  {
    slug: "stb-xay-sua",
    bankId: "stb",
    ten: "Xây sửa nhà Sacombank",
    loai: "the-chap",
    muc_dich: ["xay-sua"],
    tsdb: ["so-do", "so-hong"],
    lai_suat_uu_dai: 6.8,
    thang_uu_dai: 12,
    bien_do: 3.6,
    lai_suat_co_so: 5.7,
    han_muc_min: 100,
    han_muc_max: 8000,
    ltv: 70,
    thoi_han_max: 240,
    giai_ngan_ngay: 12,
    thu_nhap_min: 15,
    phi_tra_truoc_han: "1,5% năm 1–2",
    phi_tham_dinh: "1,5 triệu",
    diem: 4.1,
    uu_diem: ["Giải ngân theo tiến độ thi công", "Chấp nhận nhà chưa hoàn công"],
    nhuoc_diem: ["Hồ sơ cần bản vẽ và dự toán", "Lãi suất trung bình"],
  },
  {
    slug: "shb-tieu-dung-tc",
    bankId: "shb",
    ten: "Tiêu dùng có tài sản",
    loai: "the-chap",
    muc_dich: ["tieu-dung"],
    tsdb: ["so-do", "so-hong", "can-ho"],
    lai_suat_uu_dai: 7.2,
    thang_uu_dai: 6,
    bien_do: 3.9,
    lai_suat_co_so: 5.8,
    han_muc_min: 100,
    han_muc_max: 5000,
    ltv: 65,
    thoi_han_max: 120,
    giai_ngan_ngay: 8,
    thu_nhap_min: 12,
    phi_tra_truoc_han: "1% mọi thời điểm",
    phi_tham_dinh: "Miễn phí",
    diem: 4.0,
    uu_diem: ["Phí trả trước hạn thấp nhất", "Hồ sơ đơn giản"],
    nhuoc_diem: ["Ưu đãi chỉ 6 tháng", "Tỷ lệ vay tối đa 65%"],
  },
  {
    slug: "vpb-luong-chuyen-khoan",
    bankId: "vpb",
    ten: "Vay theo lương chuyển khoản",
    loai: "tin-chap",
    nhom: ["chuyen-khoan"],
    lai_suat_uu_dai: 12.5,
    thang_uu_dai: 0,
    bien_do: 0,
    lai_suat_co_so: 12.5,
    han_muc_min: 10,
    han_muc_max: 500,
    thoi_han_max: 60,
    giai_ngan_ngay: 1,
    thu_nhap_min: 8,
    bhxh_thang: 6,
    phi_tra_truoc_han: "3% dư nợ còn lại",
    phi_tham_dinh: "Miễn phí",
    diem: 4.6,
    uu_diem: ["Giải ngân trong 24 giờ", "Hạn mức tới 500 triệu", "Không cần tài sản đảm bảo"],
    nhuoc_diem: ["Bắt buộc lương chuyển khoản", "Phí trả nợ trước hạn 3%"],
  },
  {
    slug: "tpb-luong-nhanh",
    bankId: "tpb",
    ten: "Vay nhanh theo lương",
    loai: "tin-chap",
    nhom: ["chuyen-khoan"],
    lai_suat_uu_dai: 13.9,
    thang_uu_dai: 0,
    bien_do: 0,
    lai_suat_co_so: 13.9,
    han_muc_min: 10,
    han_muc_max: 300,
    thoi_han_max: 60,
    giai_ngan_ngay: 1,
    thu_nhap_min: 7,
    bhxh_thang: 3,
    phi_tra_truoc_han: "2% dư nợ còn lại",
    phi_tham_dinh: "Miễn phí",
    diem: 4.4,
    uu_diem: ["Chỉ cần BHXH 3 tháng", "Duyệt online hoàn toàn", "Phí trả trước hạn thấp"],
    nhuoc_diem: ["Hạn mức tối đa 300 triệu", "Lãi suất cao hơn VPBank"],
  },
  {
    slug: "mb-luong-tien-mat",
    bankId: "mb",
    ten: "Vay theo bảng lương",
    loai: "tin-chap",
    nhom: ["tien-mat", "chuyen-khoan"],
    lai_suat_uu_dai: 18.5,
    thang_uu_dai: 0,
    bien_do: 0,
    lai_suat_co_so: 18.5,
    han_muc_min: 10,
    han_muc_max: 200,
    thoi_han_max: 48,
    giai_ngan_ngay: 2,
    thu_nhap_min: 6,
    bhxh_thang: 6,
    phi_tra_truoc_han: "3% dư nợ còn lại",
    phi_tham_dinh: "Miễn phí",
    diem: 4.2,
    uu_diem: ["Chấp nhận lương tiền mặt", "Chỉ cần bảng lương có dấu"],
    nhuoc_diem: ["Lãi suất cao", "Hạn mức tối đa 200 triệu"],
  },
  {
    slug: "hdb-bao-hiem",
    bankId: "hdb",
    ten: "Vay theo hợp đồng bảo hiểm",
    loai: "tin-chap",
    nhom: ["bao-hiem"],
    lai_suat_uu_dai: 16.9,
    thang_uu_dai: 0,
    bien_do: 0,
    lai_suat_co_so: 16.9,
    han_muc_min: 20,
    han_muc_max: 300,
    thoi_han_max: 60,
    giai_ngan_ngay: 2,
    thu_nhap_min: 7,
    bhxh_thang: 0,
    phi_tra_truoc_han: "3% dư nợ còn lại",
    phi_tham_dinh: "Miễn phí",
    diem: 4.3,
    uu_diem: ["Không cần sao kê lương", "Không yêu cầu BHXH", "Nhận hồ sơ tự kinh doanh"],
    nhuoc_diem: ["Cần hợp đồng đóng phí trên 12 tháng", "Phí năm tối thiểu 10 triệu"],
  },
  {
    slug: "seab-hoa-don",
    bankId: "seab",
    ten: "Vay theo hóa đơn điện nước",
    loai: "tin-chap",
    khu_vuc: DO_THI_LON,
    nhom: ["hoa-don"],
    lai_suat_uu_dai: 22.5,
    thang_uu_dai: 0,
    bien_do: 0,
    lai_suat_co_so: 22.5,
    han_muc_min: 10,
    han_muc_max: 70,
    thoi_han_max: 36,
    giai_ngan_ngay: 2,
    thu_nhap_min: 5,
    bhxh_thang: 0,
    phi_tra_truoc_han: "4% dư nợ còn lại",
    phi_tham_dinh: "Miễn phí",
    diem: 3.8,
    uu_diem: ["Hồ sơ đơn giản nhất", "Không cần chứng minh thu nhập chính thức"],
    nhuoc_diem: ["Lãi suất cao nhất nhóm", "Hạn mức tối đa 70 triệu"],
  },
  {
    slug: "acb-tin-chap-cao-cap",
    bankId: "acb",
    ten: "Tín chấp khách hàng ưu tiên",
    loai: "tin-chap",
    khu_vuc: ["TP. Hồ Chí Minh", "Hà Nội"],
    nhom: ["chuyen-khoan"],
    lai_suat_uu_dai: 11.9,
    thang_uu_dai: 0,
    bien_do: 0,
    lai_suat_co_so: 11.9,
    han_muc_min: 100,
    han_muc_max: 500,
    thoi_han_max: 60,
    giai_ngan_ngay: 2,
    thu_nhap_min: 25,
    bhxh_thang: 12,
    phi_tra_truoc_han: "2% dư nợ còn lại",
    phi_tham_dinh: "Miễn phí",
    diem: 4.7,
    uu_diem: ["Lãi suất tín chấp thấp nhất", "Hạn mức tới 500 triệu"],
    nhuoc_diem: ["Yêu cầu thu nhập từ 25 triệu", "Cần BHXH 12 tháng"],
  },
  {
    slug: "tcb-tin-chap-luong",
    bankId: "tcb",
    ten: "Ứng lương linh hoạt",
    loai: "tin-chap",
    nhom: ["chuyen-khoan"],
    lai_suat_uu_dai: 14.5,
    thang_uu_dai: 0,
    bien_do: 0,
    lai_suat_co_so: 14.5,
    han_muc_min: 10,
    han_muc_max: 400,
    thoi_han_max: 60,
    giai_ngan_ngay: 1,
    thu_nhap_min: 10,
    bhxh_thang: 6,
    phi_tra_truoc_han: "3% dư nợ còn lại",
    phi_tham_dinh: "Miễn phí",
    diem: 4.5,
    uu_diem: ["Giải ngân trong ngày", "Có thể vay lại sau 6 kỳ trả đúng hạn"],
    nhuoc_diem: ["Chỉ nhận lương qua Techcombank", "Phí trả trước hạn 3%"],
  },
  {
    slug: "vib-tin-chap-tu-kinh-doanh",
    bankId: "vib",
    ten: "Tín chấp hộ kinh doanh",
    loai: "tin-chap",
    khu_vuc: DO_THI_LON,
    nhom: ["tien-mat", "bao-hiem"],
    lai_suat_uu_dai: 19.9,
    thang_uu_dai: 0,
    bien_do: 0,
    lai_suat_co_so: 19.9,
    han_muc_min: 20,
    han_muc_max: 250,
    thoi_han_max: 48,
    giai_ngan_ngay: 3,
    thu_nhap_min: 10,
    bhxh_thang: 0,
    phi_tra_truoc_han: "3% dư nợ còn lại",
    phi_tham_dinh: "Miễn phí",
    diem: 4.0,
    uu_diem: ["Nhận hộ kinh doanh cá thể", "Không yêu cầu BHXH"],
    nhuoc_diem: ["Cần giấy phép kinh doanh 12 tháng", "Lãi suất cao"],
  },
];

export const productBySlug = (slug) => products.find((p) => p.slug === slug);

export const MUC_DICH = [
  { id: "mua-nha", label: "Mua nhà, căn hộ" },
  { id: "xay-sua", label: "Xây, sửa nhà" },
  { id: "mua-xe", label: "Mua ô tô" },
  { id: "kinh-doanh", label: "Vốn kinh doanh" },
  { id: "tieu-dung", label: "Tiêu dùng" },
];

export const TSDB = [
  { id: "so-do", label: "Sổ đỏ (đất thổ cư)" },
  { id: "so-hong", label: "Sổ hồng (nhà riêng)" },
  { id: "can-ho", label: "Căn hộ dự án" },
  { id: "o-to", label: "Ô tô" },
];

export const TINH_THANH = [
  "TP. Hồ Chí Minh", "Hà Nội", "Đà Nẵng", "Bình Dương", "Đồng Nai",
  "Hải Phòng", "Cần Thơ", "Khánh Hòa", "Bà Rịa - Vũng Tàu", "Long An",
  "Bắc Ninh", "Quảng Ninh", "Nghệ An", "Thanh Hóa", "Lâm Đồng",
];

export const articles = [
  {
    slug: "lai-suat-tha-noi-la-gi",
    tieu_de: "Lãi suất thả nổi là gì và vì sao khoản trả hàng tháng của bạn tăng gấp rưỡi",
    mo_ta: "Con số 5,5% trên quảng cáo chỉ tồn tại 12 tháng. Đây là cách tính khoản trả thật cho 24 năm còn lại.",
    chuyen_muc: "Vay thế chấp",
    tac_gia: "Nguyễn Minh Đức",
    chuc_danh: "Chuyên viên phân tích tín dụng, 11 năm kinh nghiệm",
    kiem_duyet: "Trần Thu Hà, CFA",
    ngay: "18/07/2026",
    doc_phut: 8,
  },
  {
    slug: "no-xau-cic-con-vay-duoc-khong",
    tieu_de: "Nợ xấu CIC nhóm 2: bạn còn vay được ở đâu và sau bao lâu thì hết",
    mo_ta: "Phân biệt 5 nhóm nợ, thời gian lưu trữ lịch sử và những ngân hàng vẫn xét duyệt hồ sơ nhóm 2.",
    chuyen_muc: "Vay tín chấp",
    tac_gia: "Lê Hoàng Nam",
    chuc_danh: "Cựu chuyên viên thẩm định, 9 năm kinh nghiệm",
    kiem_duyet: "Trần Thu Hà, CFA",
    ngay: "15/07/2026",
    doc_phut: 6,
  },
  {
    slug: "vay-luong-tien-mat",
    tieu_de: "Nhận lương tiền mặt vẫn vay được: 4 cách chứng minh thu nhập ngân hàng chấp nhận",
    mo_ta: "Bảng lương có dấu, sổ BHXH, hóa đơn điện nước và hợp đồng bảo hiểm nhân thọ.",
    chuyen_muc: "Vay tín chấp",
    tac_gia: "Phạm Thị Quỳnh",
    chuc_danh: "Chuyên viên tư vấn tín dụng cá nhân",
    kiem_duyet: "Trần Thu Hà, CFA",
    ngay: "12/07/2026",
    doc_phut: 7,
  },
  {
    slug: "tinh-kha-nang-tra-no",
    tieu_de: "Quy tắc 40%: cách ngân hàng tính bạn được vay bao nhiêu",
    mo_ta: "Tổng nghĩa vụ trả nợ hàng tháng không nên vượt 40% thu nhập. Đây là cách áp dụng vào hồ sơ thật.",
    chuyen_muc: "Kiến thức chung",
    tac_gia: "Nguyễn Minh Đức",
    chuc_danh: "Chuyên viên phân tích tín dụng, 11 năm kinh nghiệm",
    kiem_duyet: "Trần Thu Hà, CFA",
    ngay: "08/07/2026",
    doc_phut: 5,
  },
  {
    slug: "phi-tra-no-truoc-han",
    tieu_de: "Phí trả nợ trước hạn: khoản chi phí ít ai đọc kỹ trong hợp đồng vay",
    mo_ta: "Trả sớm 1 tỷ có thể mất 20 triệu tiền phí. So sánh biểu phí của 12 ngân hàng.",
    chuyen_muc: "Vay thế chấp",
    tac_gia: "Lê Hoàng Nam",
    chuc_danh: "Cựu chuyên viên thẩm định, 9 năm kinh nghiệm",
    kiem_duyet: "Trần Thu Hà, CFA",
    ngay: "02/07/2026",
    doc_phut: 6,
  },
  {
    slug: "nhan-biet-lua-dao-vay-tien",
    tieu_de: "6 dấu hiệu của một app vay tiền lừa đảo",
    mo_ta: "Yêu cầu phí trước giải ngân, duyệt 100% không cần giấy tờ, ép cài app ngoài kho ứng dụng.",
    chuyen_muc: "Cảnh báo",
    tac_gia: "Phạm Thị Quỳnh",
    chuc_danh: "Chuyên viên tư vấn tín dụng cá nhân",
    kiem_duyet: "Trần Thu Hà, CFA",
    ngay: "28/06/2026",
    doc_phut: 5,
  },
];

export const articleBySlug = (slug) => articles.find((a) => a.slug === slug);

export const seedLeads = [
  {
    id: "MB-24071",
    ho_ten: "Nguyễn Văn Hùng",
    dien_thoai: "0903 xxx 412",
    loai: "the-chap",
    so_tien: 2000,
    thoi_han: 240,
    muc_dich: "mua-nha",
    tsdb: "can-ho",
    gia_tri_tsdb: 3000,
    thu_nhap: 45,
    hinh_thuc_luong: "chuyen-khoan",
    nghe: "Nhân viên văn phòng",
    bhxh: 60,
    tinh: "TP. Hồ Chí Minh",
    nam_sinh: 1988,
    no_hien_tai: false,
    trang_thai: "da-chuyen-nh",
    nguon: "google / organic",
    trang_vao: "/vay-the-chap",
    phu_trach: "Trần Thu Hà",
    tao_luc: "26/07/2026 09:12",
    ngan_hang: "vcb",
    lich_su: [
      { luc: "26/07 09:12", noi_dung: "Lead vào hệ thống từ trang vay thế chấp", loai: "he-thong" },
      { luc: "26/07 09:40", noi_dung: "Gọi lần 1 — khách bắt máy, xác nhận nhu cầu 2 tỷ mua căn hộ Vinhomes", loai: "goi" },
      { luc: "26/07 10:15", noi_dung: "Đã gửi hồ sơ sang RM Vietcombank chi nhánh Tân Bình", loai: "chuyen" },
    ],
  },
  {
    id: "MB-24070",
    ho_ten: "Trần Thị Lan",
    dien_thoai: "0912 xxx 887",
    loai: "tin-chap",
    so_tien: 80,
    thoi_han: 36,
    thu_nhap: 15,
    hinh_thuc_luong: "chuyen-khoan",
    nghe: "Nhân viên văn phòng",
    bhxh: 18,
    tinh: "TP. Hồ Chí Minh",
    nam_sinh: 1997,
    no_hien_tai: true,
    trang_thai: "dang-tu-van",
    nguon: "facebook / cpc",
    trang_vao: "/vay-tin-chap",
    phu_trach: "Lê Hoàng Nam",
    tao_luc: "26/07/2026 08:47",
    ngan_hang: null,
    lich_su: [
      { luc: "26/07 08:47", noi_dung: "Lead vào hệ thống từ trang vay tín chấp", loai: "he-thong" },
      { luc: "26/07 09:05", noi_dung: "Gọi lần 1 — không bắt máy", loai: "goi" },
      { luc: "26/07 09:30", noi_dung: "Nhắn Zalo, khách phản hồi hẹn gọi lại sau 18h", loai: "ghi-chu" },
    ],
  },
  {
    id: "MB-24069",
    ho_ten: "Phạm Quốc Bảo",
    dien_thoai: "0987 xxx 203",
    loai: "the-chap",
    so_tien: 800,
    thoi_han: 120,
    muc_dich: "kinh-doanh",
    tsdb: "so-do",
    gia_tri_tsdb: 1500,
    thu_nhap: 60,
    hinh_thuc_luong: "tu-kinh-doanh",
    nghe: "Hộ kinh doanh",
    bhxh: 0,
    tinh: "Bình Dương",
    nam_sinh: 1985,
    no_hien_tai: false,
    trang_thai: "da-giai-ngan",
    nguon: "google / cpc",
    trang_vao: "/so-sanh",
    phu_trach: "Trần Thu Hà",
    tao_luc: "24/07/2026 14:20",
    ngan_hang: "vpb",
    lich_su: [
      { luc: "24/07 14:20", noi_dung: "Lead vào hệ thống từ trang so sánh", loai: "he-thong" },
      { luc: "24/07 15:02", noi_dung: "Gọi lần 1 — xác nhận hồ sơ, hẹn nộp giấy tờ", loai: "goi" },
      { luc: "25/07 09:00", noi_dung: "Chuyển hồ sơ sang VPBank", loai: "chuyen" },
      { luc: "26/07 11:30", noi_dung: "Ngân hàng báo đã giải ngân 800 triệu", loai: "he-thong" },
    ],
  },
  {
    id: "MB-24068",
    ho_ten: "Vũ Thị Mai",
    dien_thoai: "0938 xxx 155",
    loai: "tin-chap",
    so_tien: 50,
    thoi_han: 24,
    thu_nhap: 9,
    hinh_thuc_luong: "tien-mat",
    nghe: "Công nhân",
    bhxh: 24,
    tinh: "Đồng Nai",
    nam_sinh: 1993,
    no_hien_tai: false,
    trang_thai: "moi",
    nguon: "google / organic",
    trang_vao: "/vay-tin-chap",
    phu_trach: null,
    tao_luc: "26/07/2026 10:03",
    ngan_hang: null,
    lich_su: [{ luc: "26/07 10:03", noi_dung: "Lead vào hệ thống từ trang vay tín chấp", loai: "he-thong" }],
  },
  {
    id: "MB-24067",
    ho_ten: "Đỗ Minh Tuấn",
    dien_thoai: "0977 xxx 641",
    loai: "the-chap",
    so_tien: 1200,
    thoi_han: 180,
    muc_dich: "mua-xe",
    tsdb: "o-to",
    gia_tri_tsdb: 1500,
    thu_nhap: 38,
    hinh_thuc_luong: "chuyen-khoan",
    nghe: "Quản lý",
    bhxh: 84,
    tinh: "Hà Nội",
    nam_sinh: 1990,
    no_hien_tai: true,
    trang_thai: "tu-choi",
    nguon: "zalo / cpc",
    trang_vao: "/cong-cu/tinh-khoan-vay",
    phu_trach: "Lê Hoàng Nam",
    tao_luc: "23/07/2026 16:40",
    ngan_hang: "vib",
    lich_su: [
      { luc: "23/07 16:40", noi_dung: "Lead vào hệ thống từ công cụ tính khoản vay", loai: "he-thong" },
      { luc: "23/07 17:10", noi_dung: "Gọi lần 1 — khách đang có 2 khoản vay khác", loai: "goi" },
      { luc: "25/07 10:00", noi_dung: "VIB từ chối do tỷ lệ nợ trên thu nhập vượt 55%", loai: "he-thong" },
    ],
  },
  {
    id: "MB-24066",
    ho_ten: "Hoàng Thị Thu",
    dien_thoai: "0909 xxx 730",
    loai: "tin-chap",
    so_tien: 150,
    thoi_han: 48,
    thu_nhap: 22,
    hinh_thuc_luong: "chuyen-khoan",
    nghe: "Giáo viên",
    bhxh: 96,
    tinh: "Đà Nẵng",
    nam_sinh: 1989,
    no_hien_tai: false,
    trang_thai: "da-chuyen-nh",
    nguon: "google / organic",
    trang_vao: "/goi-vay/acb-tin-chap-cao-cap",
    phu_trach: "Trần Thu Hà",
    tao_luc: "25/07/2026 11:22",
    ngan_hang: "acb",
    lich_su: [
      { luc: "25/07 11:22", noi_dung: "Lead vào hệ thống từ trang chi tiết gói ACB", loai: "he-thong" },
      { luc: "25/07 11:50", noi_dung: "Gọi lần 1 — hồ sơ đẹp, đủ điều kiện gói ưu tiên", loai: "goi" },
      { luc: "25/07 14:00", noi_dung: "Chuyển hồ sơ sang ACB", loai: "chuyen" },
    ],
  },
];

export const TRANG_THAI = {
  moi: { label: "Mới", mau: "bg-steel-100 text-steel-700" },
  "dang-tu-van": { label: "Đang tư vấn", mau: "bg-signal-light text-signal" },
  "da-chuyen-nh": { label: "Đã chuyển ngân hàng", mau: "bg-brand-light text-brand-dark" },
  "da-giai-ngan": { label: "Đã giải ngân", mau: "bg-brand text-white" },
  "tu-choi": { label: "Từ chối", mau: "bg-alert-light text-alert" },
};

export const bieu_do_nguon = [
  { nguon: "Google tự nhiên", lead: 412, giai_ngan: 38 },
  { nguon: "Google quảng cáo", lead: 286, giai_ngan: 21 },
  { nguon: "Facebook", lead: 194, giai_ngan: 9 },
  { nguon: "Zalo OA", lead: 121, giai_ngan: 11 },
  { nguon: "Trực tiếp", lead: 87, giai_ngan: 7 },
];

export const bieu_do_pheu = [
  { buoc: "Bước 1 — Nhu cầu", so_nguoi: 4820 },
  { buoc: "Bước 2 — Tài sản", so_nguoi: 3410 },
  { buoc: "Bước 3 — Thu nhập", so_nguoi: 2180 },
  { buoc: "Bước 4 — Khu vực", so_nguoi: 1640 },
  { buoc: "Bước 5 — Liên hệ", so_nguoi: 1100 },
];

export const bieu_do_thang = [
  { thang: "T2", lead: 620, giai_ngan: 41 },
  { thang: "T3", lead: 710, giai_ngan: 52 },
  { thang: "T4", lead: 845, giai_ngan: 63 },
  { thang: "T5", lead: 910, giai_ngan: 71 },
  { thang: "T6", lead: 1024, giai_ngan: 78 },
  { thang: "T7", lead: 1100, giai_ngan: 86 },
];
